### ISSUE TITLE
Quick Start?

### ISSUE THREAD

**Issue by prologic** [bnema/gordon#1]
Please provide a quick start in the README.

Alternatively (or both) a Docker image would also be quite nice.

I'd love to see where you're going with this 👌

**Comment by bnema** [comment]
As soon as the 0.1 is released, I'll provide a wiki and a quick start guide. I'm still missing 2 key features but thank you for your interest 🙌

**Comment by prologic** [comment]
Thanks! 🙏

**Comment by bnema** [comment]
@prologic The 0.1 is released with the essential features if you want to take a look: https://github.com/bnema/gordon/releases/tag/0.1

I've also opened a discussion thread https://github.com/bnema/gordon/discussions/2

Have a great day !
